export const RESOURCE = [
  // Vietnamese
  {
    'adminTitle': 'Hệ thống phản hồi công dân',
    'username': 'Tài khoản',
    'unitName': 'Tên đơn vị',
    'unitLevel': 'Cấp đơn vị',
    'selectUnitLevel': 'Chọn cấp đơn vị',
    'receivedNotice': 'Có nhận mail?',
    'receivedNoticeTrue': 'Nhận mail thông báo',
    'receivedNoticeFalse': 'Không Nhận mail thông báo',
    'listUser': 'Danh sách người dùng',
    'listServices': 'Danh sách chủ đề',
    'password': 'Mật khẩu',
    'rePassword': 'Xác nhận mật khẩu',
    'rememberMe': 'Lưu thông tin đăng nhập',
    'signIn': 'Đăng nhập',
    'backToSignIn': 'Quay lại trang đăng nhập',
    'dashBroad': 'Bảng thông tin',
    'managerUser': 'Quản lý người dùng',
    'managerUnit': 'Quản lý đơn vị',
    'configUnit': 'Cấu hình đơn vị',
    'managerRequest': 'Quản lý phản hồi',
    'managerDocument': 'Quản lý tài liệu',
    'managerService': 'Quản lý chủ đề',
    'managerFaq': 'Quản lý câu hỏi',
    'managerReport': 'Quản lý báo cáo',
    'reportStatistical': 'Báo cáo thống kê',
    'managerPermissions': 'Quản lý nhóm quyền',
    'settings': 'Cấu hình',
    'home': 'Trang Chủ',
    'email': 'Email',
    'fullName': 'Họ và tên',
    'userType': 'Vai trò',
    'position': 'Chức vụ',
    'department': 'Phòng ban',
    'mobilePhone': 'Số điện thoại',
    'telePhone': 'Điện thoại',
    'socialLink': 'Tài khoản mạng xã hội',
    'edit': 'Cập nhật',
    'delete': 'Xóa',
    'note': 'Thông tin khác',
    'superAdmin': 'Admin',
    'role': 'Vai trò',
    'System admin': 'Quản trị hệ thống',
    'Manager': 'Quản lý',
    'Staff': 'Nhân viên',
    'submitedRequest': 'Tiếp nhận',
    'openedRequest': 'Đang xử lý',
    'closeRequest': 'Đã xử lý',
    'latestRequest': 'Số phản hồi mới nhất',
    'detailRequest': 'Xem chi tiết',
    'no': 'STT',
    'title': 'Tiêu đề',
    'service': 'Chủ đề',
    'createDate': 'Ngày tạo',
    'location': 'Vị trí',
    'state': 'Trạng thái',
    'questionDelete': 'Bạn muốn xóa bản ghi này?',
    'device': 'Thiết bị',
    'viewAll': 'Xem tất cả',
    'profile': 'Hồ sơ',
    'signOut': 'Đăng xuất',
    'youHave': 'Bạn có',
    'notification': 'Phản hồi',
    'settingFormDetail': 'Thông tin cấu hình',
    'updateButton': 'Cập nhật',
    'cancelButton': 'Hủy',
    'deleteButton': 'Xóa',
    'stopButton': 'Ngừng hoạt động',
    'buttonAddNew': 'Thêm mới',
    'latitude': 'Vĩ độ',
    'longtitude': 'Kinh độ',
    'topRequest': 'Số chủ đề hàng đầu',
    'itemPerPage': 'Số lượng phản hồi mỗi trang',
    'updateSettingSuccess': 'Thay đổi thông tin cấu hình thành công',
    'updateSettingFail': 'Thay đổi thông tin cấu hình thất bại. Vui lòng thử lại',
    'latitudeRequire': 'Vĩ độ không được để trống',
    'longtitudeRequire': 'Kinh độ không được để trống',
    'topRequestRequire': 'Số chủ đề hàng đầu không được để trống',
    'itemPerPageRequire': 'Số lượng phản hồi mỗi trang không được để trống',
    'latestRequestRequire': 'Số lượng phản hồi mới nhât không được để trống',
    'socialNetwork': 'Tài khoản mạng xã hội',
    'telephone': 'Điện thoại',
    'address': 'Địa chỉ',
    'deleteOneSucess': 'Xóa thành công.',
    'deleteOneFailed': 'Xóa không thành công.',
    'profileDetail': 'Thông tin cá nhân',
    'changePassword': 'Thay đổi mật khẩu',
    'fullNameRequire': 'Tên đầy đủ không được để trống.',
    'emailRequire': 'Email không được để trống.',
    'duplicateUsername': 'Tài khoản đã tồn tại.',
    'duplicateUnitName': 'Đơn vị đã tồn tại.',
    'updateProfileSuccess': 'Thay đổi thông tin thành công.',
    'updateProfileFail': 'Thay đổi thông tin thất bại, vui lòng thử lại.',
    'emailInvalid': 'Email không hợp lệ',
    'oldPassword': 'Mật khẩu cũ',
    'newPassword': 'Mật khẩu mới',
    'reNewPassword': 'Nhập lại mật khẩu mới',
    'sendForgotPassword': 'Gửi email',
    'oldPasswordRequire': 'Mât khẩu cũ không được để trống.',
    'newPasswordRequire': 'Mật khẩu mới không được để trống.',
    'oldPasswordError': 'Sai mật khẩu cũ',
    'reNewPasswordRequire': 'Mật khẩu nhập lại không được để trống.',
    'passwordLengthError': 'Độ dài mật khẩu phải lớn hơn hoặc bằng 8 ký tự.',
    'rePasswordError': 'Mật khẩu xác nhận không khớp. Hãy thử lại!',
    'oldAndNewPassError': 'Mật khẩu mới và cũ không được trùng nhau.',
    'newPassError': 'Mật khẩu nhập lại không đúng.',
    'updatePasswordSuccess': 'Thay đổi mật khẩu thành công.',
    'updatePasswordFail': 'Thay đổi mật khẩu thất bại, vui lòng thử lại.',
    'oldPassError': 'Mật khẩu cũ nhập lại không đúng',
    'report': 'Quản lý báo cáo',
    'reportState': 'Trạng thái',
    'reportService': 'Chủ đề',
    'addUser': 'Thêm người dùng',
    'addUnit': 'Thêm đơn vị',
    'deleteMultiUser': 'Xoá nhiều người dùng',
    'deleteMultiUnit': 'Xoá nhiều đơn vị',
    'deleteUser': 'Xóa người dùng',
    'editUser': 'Cập nhật thông tin người dùng',
    'editUnit': 'Cập nhật thông tin đơn vị',
    'backButton': 'Quay lại',
    'addButton': 'Tạo',
    'editButton': 'Cập nhật thông tin',
    'deleteUserConfirmMessage': 'Bạn muốn xóa người dùng này?',
    'deleteUserUnitConfirmMessage': 'Bạn muốn xóa người dùng này khỏi đơn vị?',
    'deleteUserNoRecordSelected': 'Chưa có người dùng nào được chọn!',
    'deleteUnitConfirmMessage': 'Bạn muốn xóa đơn vị này?',
    'deleteUnitNoRecordSelected': 'Chưa có đơn vị nào được chọn!',
    'addFaq': 'Thêm câu hỏi',
    'deleteMultiFaq': 'Xóa nhiều câu hỏi',
    'deleteFaq': 'Xóa câu hỏi',
    'editFaq': 'Cập nhật câu hỏi',
    'deleteFaqConfirmMessage': 'Bạn muốn xóa câu hỏi này?',
    'deleteFaqNoRecordSelected': 'Chưa có câu hỏi nào được chọn!',
    'deleteFaqSucess': 'Xóa câu hỏi thành công',
    'deleteFaqFailed': 'Xóa câu hỏi không thành công',
    'description': 'Nội dung',
    'questionError': 'Câu hỏi không được để trống',
    'answerError': 'Câu trả lời không được để trống',
    'deleteMultiRequest': 'Xóa nhiều phản hồi',
    'deleteRequest': 'Xóa phản hồi',
    'editRequest': 'Xử lý phản hồi',
    'deleteRequestConfirmMessage': 'Bạn muốn xóa phản hồi này?',
    'deleteRequestNoRecordSelected': 'Chưa có phản hồi nào được chọn!',
    'deleteRequestSucess': 'Xóa phản hồi thành công',
    'deleteRequestFailed': 'Xóa phản hồi không thành công',
    'imageSubmitted': 'Ảnh báo cáo',
    'imageClosed': 'Ảnh hoàn thành',
    'phone': 'Điện thoại',
    'submitted': 'Tiếp nhận',
    'open': 'Đang xử lý',
    'close': 'Đã xử lý',
    'lastName': 'Họ',
    'firstName': 'Tên',
    'question': 'Câu hỏi',
    'answer': 'Câu trả lời',
    'googleApi': 'Google Api Key',
    'zoom': 'Zoom',
    'facebookApi': 'Facebook Api Key',
    'totalMembers': 'Số thành viên',
    'emailsReceive': 'Email nhận phản hồi',
    'googleApiRequire': 'Google Api Key không được để trống',
    'zoomRequire': 'Độ zoom của map không được để trống',
    'facebookApiRequire': 'Facebook Api Key không được để trống',
    'totalMembersRequire': 'Số thành viên không được để trống',
    'emailsReceiveRequire': 'Email nhận phản hồi không được để trống',
    'emailsReceiveHelpText': 'Địa chỉ email phân cách bằng dấu ;',
    'subState': 'Cách giải quyết',
    'selectPersonInCharge': 'Chọn nhân viên',
    'selectStatus': 'Chọn trạng thái',
    'status': 'Trạng thái',
    'personInCharge': 'Nhân viên xử lý',
    'notificationToUnit': 'Thông báo tới',
    'caseWarning': 'Đã cảnh cáo',
    'caseFines': 'Xử lý nộp phạt',
    'caseNotExits': 'Không tồn tại',
    'caseResolved': 'Đã xử lý',
    'caseDuplicate': 'Đã tồn tại',
    'caseViolationFiled': 'Đã nộp phạt',
    'caseViolationCorrected': 'Đã sửa đổi',
    'avatar': 'Ảnh đại diện',
    'anonymous': 'Một người giấu tên',
    'googleClientId': 'Google Client Id',
    'googleRecaptchaKey': 'Google Recaptcha Key',
    'googleClientIdRequire': 'Google Client Id không được để trống',
    'googleRecaptchaKeyRequire': 'Google Recaptcha không được để trống',
    'addService': 'Thêm chủ đề',
    'deleteMultiService': 'Xóa nhiều chủ đề',
    'deleteService': 'Xóa chủ đề',
    'editService': 'Cập nhật chủ đề',
    'unitsOutsideTheManagement': 'Không có quyền quản lý chủ đề thuộc đơn vị khác',
    'deleteServiceConfirmMessage': 'Bạn muốn xóa chủ đề này và các phản hồi liên quan?',
    'deleteServiceNoRecordSelected': 'Chưa có chủ đề nào được chọn!',
    'deleteServiceSucess': 'Xóa chủ đề thành công',
    'deleteServiceFailed': 'Xóa chủ đề không thành công',
    'requestNote': 'Ghi chú',
    'updateBy': 'Cập nhật bởi',
    'requestAnswer': 'Trả lời phản hồi',
    'location': 'Vị trí',
    'placeholder_location': 'Nhập vị trí',
    'request_heading': 'Phản hồi',
    'request_location': 'Vị trí phản hồi',
    'manageService': 'Quản lý chủ đề',
    'removeService': 'Cập nhật chủ đề',
    'serviceName': 'Tên chủ đề',
    'serviceDesc': 'Mô tả chủ đề',
    'inforLoginIncorrect': 'Thông tin đăng nhập không chính xác',
    'forgetPasswordLabel': 'Hãy nhập email đăng kí khi tạo tài khoản',
    'sendNewPasswordLabel': 'Mật khẩu mới đã được gửi vào email của bạn.',
    'emailIncorrect': 'Email nhập không đúng email đã đăng ký.',
    'forgetPasswordTitle': 'Đặt lại mật khẩu',
    'emailExistError': 'Địa chỉ email đã tồn tại',
    'deleteServiceSucess': 'Xóa chủ đề thành công',
    'deleteServiceFailed': 'Xóa chủ đề không thành công',
    'category': 'Lĩnh vực',
    'startDate': 'Từ ngày',
    'endDate': 'Đến ngày',
    'phoneReceive': 'Sdt nhận phản hồi',
    'phoneReceiveRequire': 'Sdt nhận phản hồi không được để trống',
    'filterButton': 'Lọc',
    'week': 'Tuần',
    'thisWeek': 'Tuần hiện tại',
    'month': 'Tháng',
    'thisMonth': 'Tháng hiện tại',
    'quarter': 'Quý',
    'thisQuarter': 'Quý hiện tại',
    'year': 'Năm',
    'thisYear': 'Năm hiện tại',
    'donutChart': 'Biểu đồ tròn',
    'statusRate': 'Tỉ lệ trạng thái phản hồi',
    'servicesRate': 'Tỉ lệ chủ đề phổ biến',
    'barChart': 'Biểu đồ cột',
    'exportCsv': 'Xuất file',
    'csvFilename': 'Danh_sách_phản_hồi.csv',
    'fileUpload': 'Tệp tin phản hồi',
    'selectFileWarming': 'Hãy chọn file để tải lên',
    'fileNotFoundError': 'Không tìm thấy file',
    'uploadError': 'Tải file bị lỗi. Xin hãy thử lại',
    'uploadButton': 'Tải lên',
    'uploadTitle': 'Tải lên tệp đính kèm',
    'topRequestMinusError': 'Số chủ đề hàng đầu không được là số âm',
    'itemPerPageMinusError': 'Số lượng phản hổi mỗi trang không được là số âm',
    'totalMembersMinusError': 'Số thành viên không được là số âm',
    'latestRequestMinusError': 'Số phản hồi mới nhất không được là số âm',
    'createServiceSuccess': 'Tạo chủ đề thành công.',
    'updateServiceSuccess': 'Thay đổi thông tin chủ đề thành công.',
    'createServiceFail': 'Tạo chủ đề không thành công. Hãy thử lại sau.',
    'updateServiceFail': 'Thay đổi thông tin chủ đề thất bại, vui lòng thử lại.',
    'serviceNameRequire': 'Tên chủ đề không được để trống',
    'usernameRequire': 'Tài khoản người dùng không được bỏ trống',
    'unitNameRequire': 'Tên đơn vị không được bỏ trống',
    'unitType': 'Loại đơn vị',
    'parentUnit': 'Đơn vị quản lý',
    'locationUnitRequire': 'Vị trí đơn vị không được bỏ trống',
    'parentUnitRequire': 'Đơn vị quản lý không được bỏ trống',
    'fullNameRequire': 'Tên đầy đủ không đươc bỏ trống',
    'passwordRequire': 'Mật khẩu không được bỏ trống',
    'serviceOtherOption': 'Tùy chọn khác',
    'serviceType': 'Kiểu',
    'serviceTextbox': 'Hộp văn bản',
    'serviceCheckbox': 'Hộp kiểm tra',
    'serviceTextarea': 'Khung văn bản',
    'serviceDropdown': 'Danh sách',
    'serviceLabel': 'Nhãn',
    'serviceValue': 'Giá trị',
    'selectImageError': 'Xin hãy chọn ảnh',
    'updateFaqSuccess': 'Thay đổi thông tin câu hỏi thành công.',
    'addFaqSuccess': 'Thêm mới thông tin câu hỏi thành công.',
    'updateFaqFail': 'Thay đổi thông tin câu hỏi thất bại, vui lòng thử lại.',
    'addFaqFail': 'Thêm mới thông tin câu hỏi thất bại, vui lòng thử lại.',
    'updateUserSuccess': 'Thay đổi thông tin người dùng thành công.',
    'addUserSuccess': 'Thêm mới thông tin người dùng thành công',
    'updateUnitSuccess': 'Thay đổi thông tin đơn vị thành công.',
    'addUnitSuccess': 'Thêm mới thông tin đơn vị thành công.',
    'updateUserFail': 'Thay đổi thông tin người dùng không thành công, vui lòng thử lại.',
    'addUserFail': 'Thêm mới thông tin người dùng không thành công, vui lòng thử lại',
    'updateUnitFail': 'Thay đổi thông tin đơn vị không thành công, vui lòng thử lại.',
    'addUnitFail': 'Thêm mới thông tin đơn vị không thành công, vui lòng thử lại.',
    'updateRequestSuccess': 'Cập nhật thông tin phản hồi thành công.',
    'updateRequestFail': 'Cập nhật thông tin phản hồi thất bại, vui lòng thử lại.',
    'requestFile': 'Tệp tin kèm theo',
    'multipleEmailHint': '(Các email được phân cách bởi dấu phẩy)',
    'multipleValueHint': '(Các giá trị được phân cách bởi dấu phẩy)',
    'multiplePhoneHint': '(Các số điện thoại được phân cách bởi dấu phẩy)',
    'chooseImage': 'Chọn ảnh',
    'chooseFile': 'Chọn tệp đính kèm',
    'hasError': 'Có lỗi vui lòng kiểm tra lại!',
    'index': 'STT',
    'listUsers': 'Danh sách nhân viên',
    'unit': 'Đơn vị',
    'listUnit': 'Danh sách đơn vị',
    'processUnit': 'Đơn vị xử lý',
    'processTime': 'Thời gian xử lý',
    'selectUnit': 'Chọn đơn vị',
    'noUnitSelected': 'Không có đơn vị được chọn',
    'history': 'Lịch sử',
    'time': 'Thời gian',
    'solvedDate': 'Ngày xử lý',
    'piority': 'Mức độ',
    'adminUrlRequire': 'Link web Hệ thống quản lý không được bỏ trống',
    'publicUrlRequire': 'Link web Công dân không được bỏ trống',
    'adminUrl': 'Link web Hệ thống quản lý',
    'publicUrl': 'Link web Công dân',
    'answerError': 'Xin hãy nhập câu trả lời',
    'userInfo': 'Thông tin người dùng',
    'searchCondition': 'Điều kiện tìm kiếm',
    'unit': 'Đơn vị',
    'apply': 'Áp dụng',
    'unitInfo': 'Thông tin đơn vị',
    'managerCategory': 'Quản lý lĩnh vực',
    'forgotPassword': 'Quên mật khẩu?',
    'birthDay': 'Ngày sinh',
    'loading': 'Đang tải dữ liệu',

    'listGroup': 'Danh sách nhóm',
    'managerGroup': 'Quản lý nhóm',
    'groupName': 'Tên nhóm',
    'code': 'Mã code'
  },
  //English
  {
    'abc': "{0} is dead, but {1} is alive! {0} {2}",
    'adminTitle': 'Citizen feedback system',
    'username': 'Username',
    'unitName': 'Unit name',
    'unitLevel': 'Unit level',
    'selectUnitLevel': 'Select unit level',
    'receivedNotice': 'Mail report?',
    'receivedNoticeTrue': 'Receive email alerts',
    'receivedNoticeFalse': 'No email notification',
    'listUser': 'List user',
    'listServices': 'List services',
    'password': 'Password',
    'rePassword': 'Confirm password',
    'rememberMe': 'Remember me',
    'signIn': 'Sign In',
    'backToSignIn': 'Back to login',
    'dashBroad': 'Dashboard',
    'managerUser': 'Manager User',
    'managerUnit': 'Manager Unit',
    'configUnit': 'Config Unit',
    'managerRequest': 'Manager Request',
    'managerDocument': 'Manager Document',
    'managerService': 'Manager Services',
    'managerReport': 'Manager Report',
    'reportStatistical': 'Report Statistical',
    'managerPermissions': 'Manager Permission',
    'settings': 'Settings',
    'home': 'Home',
    'email': 'Email',
    'fullName': 'FullName',
    'userType': 'User type',
    'position': 'Position',
    'department': 'Department',
    'mobilePhone': 'MobilePhone',
    'telePhone': 'TelePhone',
    'socialLink': 'Social Link',
    'edit': 'Edit',
    'delete': 'Delete',
    'note': 'Note',
    'superAdmin': 'Admin',
    'System admin': 'System admin',
    'Manager': 'Manager',
    'Staff': 'Staff',
    'role': 'Role',
    'submitedRequest': 'Submited',
    'openedRequest': 'Opening',
    'closeRequest': 'Close',
    'latestRequest': 'Latest Request',
    'detailRequest': 'View Details',
    'no': 'No',
    'title': 'Title',
    'service': 'Service',
    'createDate': 'Date',
    'location': 'Location',
    'state': 'State',
    'questionDelete': 'Are you sure?',
    'device': 'Device',
    'viewAll': 'View all',
    'profile': 'Profile',
    'signOut': 'Signout',
    'youHave': 'You have',
    'notification': 'notifications',
    'settingFormDetail': 'Setting Information',
    'updateButton': 'Update',
    'cancelButton': 'Cancel',
    'deleteButton': 'Delete',
    'stopButton': 'Stop',
    'buttonAddNew': 'Add new',
    'latitude': 'Latitude',
    'longtitude': 'Longtitude',
    'topRequest': 'Top services',
    'itemPerPage': 'Item Per Page',
    'updateSettingSuccess': 'Update setting success',
    'updateSettingFail': 'Update setting fail. Please try again',
    'latitudeRequire': 'Latitude cannot be null',
    'longtitudeRequire': 'Longtitude cannot be null',
    'topRequestRequire': 'Top request cannot be null',
    'itemPerPageRequire': 'Item Per Page cannot be null',
    'latestRequestRequire': 'Latest request cannot be nullg',
    'telephone': 'Telephone',
    'socialNetwork': 'SocialNetwork',
    'address': 'Address',
    'deleteOneSucess': 'Delete success',
    'deleteOneFailed': 'Delete failed',
    'profileDetail': 'Profile Information',
    'changePassword': 'Change password',
    'fullNameRequire': 'Fullname cannot be null',
    'emailRequire': 'Email cannot be null',
    'duplicateUsername': 'Duplicate username',
    'duplicateUnitName': 'Duplicate unit name.',
    'updateProfileSuccess': 'Update profile success',
    'updateProfileFail': 'Update profile fail, please try again',
    'emailInvalid': 'Email Invalid',
    'oldPassword': 'Old Password',
    'newPassword': 'New Password',
    'reNewPassword': 'Reenter new password',
    'sendForgotPassword': 'Send email',
    'oldPasswordRequire': 'Old password cannot be null',
    'newPasswordRequire': 'New password cannot be null',
    'oldPasswordError': 'Old password error',
    'reNewPasswordRequire': 'New password cannot be null',
    'passwordLengthError': 'Password length must be more than 8',
    'rePasswordError': 'Repassword error',
    'oldAndNewPassError': 'Old and new password must be different',
    'newPassError': 'Two new password must be the same',
    'updatePasswordSuccess': 'Change password success',
    'updatePasswordFail': 'Change password fail, please try again',
    'oldPassError': 'Old password incorect',
    'report': 'Report',
    'reportState': 'Report state',
    'reportService': 'Report service',
    'addUser': 'Add new user',
    'addUnit': 'Add new unit',
    'deleteMultiUser': 'Delete multi users',
    'deleteMultiUnit': 'Delete multi units',
    'deleteUser': 'Xóa người dùng',
    'editUser': 'Edit user',
    'editUnit': 'Edit unit',
    'backButton': 'Back',
    'addButton': 'Create',
    'editButton': 'Edit',
    'deleteUserConfirmMessage': 'Do you want to delete this user?',
    'deleteUserNoRecordSelected': 'Please select at least one user to delete!',
    'deleteUnitConfirmMessage': 'Do you want to delete this unit?',
    'deleteUnitNoRecordSelected': 'Please select at least one unit to delete!',
    'addFaq': 'Add Faq',
    'deleteMultiFaq': 'Delete Multi Faq',
    'deleteFaq': 'Delete Faq',
    'editFaq': 'Edit Faq',
    'deleteFaqConfirmMessage': 'Do you want to delete this faq?',
    'deleteFaqNoRecordSelected': 'Please select at least one faq to delete!',
    'deleteFaqSucess': 'Delete faq success',
    'deleteFaqFailed': 'Delete faq fail, please try again',
    'description': 'Description',
    'questionError': 'Question cannot be null',
    'answerError': 'Answer cannot be null',
    'deleteMultiRequest': 'Delete Multi Request',
    'deleteRequest': 'Delete request',
    'deleteRequestConfirmMessage': 'Do you want to delete this request?',
    'deleteRequestNoRecordSelected': 'Please select at least one request to delete!',
    'deleteRequestSucess': 'Delete request success',
    'deleteRequestFailed': 'Delete request fail, please try again',
    'editRequest': 'Edit request',
    'imageSubmitted': 'Submitted Photo',
    'imageClosed': 'Closed Photo',
    'phone': 'Phone',
    'submitted': 'Submitted',
    'open': 'Opening',
    'close': 'Close',
    'lastName': 'LastName',
    'firstName': 'FirstName',
    'question': 'Question',
    'answer': 'Answer',
    'googleApi': 'Google Api Key',
    'zoom': 'Zoom',
    'facebookApi': 'Facebook Api Key',
    'totalMembers': 'Total Members',
    'emailsReceive': 'Email receive request',
    'googleApiRequire': 'Google Api Key cannot be null',
    'zoomRequire': 'Zoom cannot be nullg',
    'facebookApiRequire': 'Facebook Api Key cannot be null',
    'totalMembersRequire': 'Số thành viên cannot be null',
    'emailsReceiveRequire': 'Email receive request cannot be null',
    'emailsReceiveHelpText': 'Emaill address split by ;',
    'subState': 'Solution',
    'selectPersonInCharge': 'Select staff',
    'selectStatus': 'Select status',
    'status': 'Status',
    'personInCharge': 'Staff',
    'notificationToUnit': 'Notify',
    'caseWarning': 'Case Warning',
    'caseFines': 'Case Fines',
    'caseNotExits': 'Case Not Exits',
    'caseResolved': 'Case Resolved',
    'caseDuplicate': 'Case Duplicate',
    'caseViolationFiled': 'Case Violation Filed ',
    'caseViolationCorrected': 'Case Violation Corrected',
    'avatar': 'Avatar',
    'anonymous': 'Anonymos',
    'googleClientId': 'Google Client Id',
    'googleRecaptchaKey': 'Google Recaptcha Key',
    'googleClientIdRequire': 'Google Client Id cannot be null',
    'googleRecaptchaKeyRequire': 'Google Recaptcha Key cannot be null',
    'addService': 'Add service ',
    'deleteMultiService': 'Delete multi service',
    'deleteService': 'Delete service',
    'editService': 'Edit Service',
    'unitsOutsideTheManagement': 'Units outside the management',
    'deleteServiceConfirmMessage': 'Do you want to delete service and all request?',
    'deleteServiceNoRecordSelected': 'Please select at least ont sevice!',
    'deleteServiceSucess': 'Delete sevice success',
    'deleteServiceFailed': 'Delete service failed',
    'requestNote': 'Note',
    'updateBy': 'Update by',
    'requestAnswer': 'Request anser',
    'location': 'Location',
    'placeholder_location': 'Enter location',
    'request_heading': 'Request',
    'request_location': 'Request location',
    'manageService': 'Service management',
    'removeService': 'Edit service',
    'serviceName': 'Service name',
    'serviceDesc': 'Service description',
    'inforLoginIncorrect': 'Username or Password incorect',
    'forgetPasswordLabel': 'Please enter your email address',
    'sendNewPasswordLabel': 'New password is sent to your email.',
    'emailIncorrect': 'Email is incorect.',
    'forgetPasswordTitle': 'Update password',
    'emailExistError': 'Email address exist',
    'deleteServiceSucess': 'Delete service success',
    'deleteServiceFailed': 'Delete service failed. Please try again',
    'category': 'Category',
    'startDate': 'Start Date',
    'endDate': 'End Date',
    'phoneReceive': 'Phone receive request',
    'phoneReceiveRequire': 'Phone receive cannot be null',
    'filterButton': 'Filter',
    'quarter': 'Quarter',
    'week': 'Week',
    'month': 'Month',
    'year': 'Year',
    'donutChart': 'Donut Chart',
    'statusRate': 'Tỉ lệ trạng thái',
    'servicesRate': 'Tỉ lệ chủ đề',
    'barChart': 'Bar Chart',
    'exportCsv': 'Export CSV',
    'csvFilename': 'List_request.csv',
    'fileUpload': 'File Upload',
    'selectFileWarming': 'Please select file to upload',
    'fileNotFoundError': 'File Not Found',
    'uploadError': 'Upload failed. Please try again',
    'uploadButton': 'Upload',
    'uploadTitle': 'Upload File',
    'topRequestMinusError': 'Top request must be > 0',
    'itemPerPageMinusError': 'Item per page must be > 0',
    'totalMembersMinusError': 'Total members must be > 0',
    'latestRequestMinusError': 'Latest request must be > 0',
    'createServiceSuccess': 'Create service successfully.',
    'updateServiceSuccess': 'Update service successfully.',
    'createServiceFail': 'Create service unsuccessfully. Please try again later.',
    'updateServiceFail': 'Update service unsuccessfully. Please try again later.',
    'serviceNameRequire': 'Service name should not be blank',
    'usernameRequire': 'Username cannot should not be blank',
    'unitNameRequire': 'Unit name cannot should not be blank',
    'unitType': 'Unit type',
    'parentUnit': 'Parent unit',
    'locationUnitRequire': 'Unit location cannot should not be blank',
    'parentUnitRequire': 'Parent unit cannot should not be blank',
    'fullNameRequire': 'Fullname should not be blank',
    'passwordRequire': 'Password should not be blank',
    'serviceOtherOption': 'Other option',
    'serviceType': 'Type',
    'serviceTextbox': 'Textbox',
    'serviceCheckbox': 'Checkbox',
    'serviceTextarea': 'Textarea',
    'serviceDropdown': 'Dropdown',
    'serviceLabel': 'Label',
    'serviceValue': 'Value',
    'selectImageError': 'Please select image',
    'updateFaqSuccess': 'Update faq success',
    'addFaqSuccess': 'Add faq success',
    'updateFaqFail': 'Update faq fail, please try again.',
    'addFaqFail': 'Add faq fail, please try again.',
    'updateUserSuccess': 'Update user success.',
    'updateUnitSuccess': 'Update unit success.',
    'updateUserFail': 'Update user fail, please try again.',
    'updateUnitFail': 'Update unit fail, please try again.',
    'updateRequestSuccess': 'Update request success.',
    'updateRequestFail': 'Update request fail, please try again.',
    'requestFile': 'Request File',
    'multipleEmailHint': '(Emails are separated by comma)',
    'multipleValueHint': '(Values are separated by comma)',
    'multiplePhoneHint': '(Phones are separated by comma)',
    'chooseImage': 'Choose image',
    'chooseFile': 'Choose file',
    'hasError': 'Please check again!',
    'index': '#',
    'listUsers': 'List User',
    'unit': 'Unit',
    'listUnit': 'List Unit',
    'processUnit': 'Process units',
    'processTime': 'Trocess time',
    'selectUnit': 'Select unit',
    'noUnitSelected': 'No unit selected',
    'history': 'History',
    'time': 'Times',
    'solvedDate': 'Solved date',
    'piority': 'Piority',
    'publicUrl': 'Link web public',
    'adminUrl': 'Link web public',
    'adminUrlRequire': 'Link web Admin can not be null',
    'publicUrlRequire': 'Link web Public can not be null',
    'answerError': 'Please import answer',
    'userInfo': 'User information',
    'searchCondition': 'search condition',
    'unit': 'Unit',
    'apply': 'Apply',
    'unitInfo': 'Unit information',
    'managerCategory': 'Manager Category',
    'forgotPassword': 'Forgot password?',
    'birthDay': 'Birth day',
    'loading': 'Loading'
  }
]