export const URL = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  USERS: '/users',
  USERS_PAGE: '/users?page={0}',
  USER_ID: "/user/{0}",
  UNITS: '/units',
  UNIT_ID: '/unit/{0}',
  REQUESTS: '/requests',
  REQUEST_ID: '/request/{0}',
  SERVICES: '/services',
  SERVICE_ID: '/service/{0}',
  CATEGORIES: '/categories',
  CATEGORY_ID: '/category/{0}',
  FAQS: '/faqs',
  FAQ_ID: '/faq/{0}',
  SETTINGS: '/settings',
  REPORT_STATISTICAL: '/report-statistical',
  FORGOT_PASSWORD: '/forgot-password',
  PERMISSIONS: '/permissions',
  PERMISSION_ID: '/permission/{0}',

  LINK_DEMO: '/link',

  GROUPS: '/groups',
  GROUP_PAGE: '/groups?page={0}',
  GROUP_ID: "/group/{0}",
};
